### ISSUE TITLE
Finish launch is not allowed.

### ISSUE THREAD

**Issue by sirgen** [Invictum/serenity-reportportal-integration#10]
Hi Iaroslav,

I've tried to use your plugin but got exception.
RP 4.1.0
Serenity BDD 1.9.4.
serenity-reportportal-integration 1.1.0
**maven-failsafe-plugin 2.19.1**

if time will try to reproduce within non prod project.

Could you please help me with it?

io.reactivex.exceptions.OnErrorNotImplementedException: Report Portal returned error
Status code: 406
Status message: Not Acceptable
Error Message: Finish launch is not allowed. Launch '5ac52005b9d8210001d82a5f' has items '[5ac52005b9d8210001d82a61,5ac52005b9d8210001d82a62,5ac52005b9d8210001d82a63,5ac52005b9d8210001d82a64,5ac52005b9d8210001d82a65,5ac52005b9d8210001d82a66,5ac52005b9d8210001d82a68,5ac52005b9d8210001d82a69,5ac52005b9d8210001d82a67,5ac52005b9d8210001d82a6a,5ac52005b9d8210001d82a6b,5ac52005b9d8210001d82a6d,5ac52005b9d8210001d82a6e,5ac52005b9d8210001d82a6f,5ac52005b9d8210001d82a6c,5ac52005b9d8210001d82a70,5ac52005b9d8210001d82a71,5ac52005b9d8210001d82a72,5ac52005b9d8210001d82a73,5ac52005b9d8210001d82a74,5ac52005b9d8210001d82a75,5ac52005b9d8210001d82a76,5ac52005b9d8210001d82a77,5ac52005b9d8210001d82a78,5ac52005b9d8210001d82a79,5ac52005b9d8210001d82a7a,5ac52006b9d8210001d82a7b,5ac52006b9d8210001d82a7c,5ac52006b9d8210001d82a7e,5ac52006b9d8210001d82a7f,5ac52006b9d8210001d82a80,5ac52006b9d8210001d82a82,5ac52006b9d8210001d82a81,5ac52006b9d8210001d82a83,5ac52006b9d8210001d82a84,5ac52006b9d8210001d82a85,5ac52006b9d8210001d82a86,5ac52006b9d8210001d82a87,5ac52006b9d8210001d82a88,5ac52023b9d8210001d82aae,5ac52023b9d8210001d82aaf,5ac52023b9d8210001d82ab0,5ac52023b9d8210001d82ab1,5ac52023b9d8210001d82ab2,5ac52023b9d8210001d82ab4,5ac52023b9d8210001d82ab3,5ac52023b9d8210001d82ab5,5ac52023b9d8210001d82ab6,5ac52023b9d8210001d82ab7,5ac52023b9d8210001d82ab8,5ac52023b9d8210001d82ab9,5ac52023b9d8210001d82aba]' with 'IN_PROGRESS' status
Error Type: FINISH_LAUNCH_NOT_ALLOWED

	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
	at io.reactivex.internal.operators.maybe.MaybeCallbackObserver.onError(MaybeCallbackObserver.java:83)
	at io.reactivex.internal.operators.maybe.MaybeSubscribeOn$SubscribeOnMaybeObserver.onError(MaybeSubscribeOn.java:96)
	at io.reactivex.internal.operators.maybe.MaybeCache.onError(MaybeCache.java:103)
	at io.reactivex.internal.operators.maybe.MaybeFromCallable.subscribeActual(MaybeFromCallable.java:50)
	at io.reactivex.Maybe.subscribe(Maybe.java:3727)
	at io.reactivex.internal.operators.maybe.MaybeCache.subscribeActual(MaybeCache.java:77)
	at io.reactivex.Maybe.subscribe(Maybe.java:3727)
	at io.reactivex.internal.operators.maybe.MaybeSubscribeOn$SubscribeTask.run(MaybeSubscribeOn.java:54)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.epam.reportportal.exception.ReportPortalException: Report Portal returned error
Status code: 406
Status message: Not Acceptable
Error Message: Finish launch is not allowed. Launch '5ac52005b9d8210001d82a5f' has items '[5ac52005b9d8210001d82a61,5ac52005b9d8210001d82a62,5ac52005b9d8210001d82a63,5ac52005b9d8210001d82a64,5ac52005b9d8210001d82a65,5ac52005b9d8210001d82a66,5ac52005b9d8210001d82a68,5ac52005b9d8210001d82a69,5ac52005b9d8210001d82a67,5ac52005b9d8210001d82a6a,5ac52005b9d8210001d82a6b,5ac52005b9d8210001d82a6d,5ac52005b9d8210001d82a6e,5ac52005b9d8210001d82a6f,5ac52005b9d8210001d82a6c,5ac52005b9d8210001d82a70,5ac52005b9d8210001d82a71,5ac52005b9d8210001d82a72,5ac52005b9d8210001d82a73,5ac52005b9d8210001d82a74,5ac52005b9d8210001d82a75,5ac52005b9d8210001d82a76,5ac52005b9d8210001d82a77,5ac52005b9d8210001d82a78,5ac52005b9d8210001d82a79,5ac52005b9d8210001d82a7a,5ac52006b9d8210001d82a7b,5ac52006b9d8210001d82a7c,5ac52006b9d8210001d82a7e,5ac52006b9d8210001d82a7f,5ac52006b9d8210001d82a80,5ac52006b9d8210001d82a82,5ac52006b9d8210001d82a81,5ac52006b9d8210001d82a83,5ac52006b9d8210001d82a84,5ac52006b9d8210001d82a85,5ac52006b9d8210001d82a86,5ac52006b9d8210001d82a87,5ac52006b9d8210001d82a88,5ac52023b9d8210001d82aae,5ac52023b9d8210001d82aaf,5ac52023b9d8210001d82ab0,5ac52023b9d8210001d82ab1,5ac52023b9d8210001d82ab2,5ac52023b9d8210001d82ab4,5ac52023b9d8210001d82ab3,5ac52023b9d8210001d82ab5,5ac52023b9d8210001d82ab6,5ac52023b9d8210001d82ab7,5ac52023b9d8210001d82ab8,5ac52023b9d8210001d82ab9,5ac52023b9d8210001d82aba]' with 'IN_PROGRESS' status
Error Type: FINISH_LAUNCH_NOT_ALLOWED

	at com.epam.reportportal.service.ReportPortalErrorHandler.handleError(ReportPortalErrorHandler.java:57)
	at com.epam.reportportal.restendpoint.http.DefaultErrorHandler.handle(DefaultErrorHandler.java:56)
	at com.epam.reportportal.restendpoint.http.HttpClientRestEndpoint$1.call(HttpClientRestEndpoint.java:487)
	at com.epam.reportportal.restendpoint.http.HttpClientRestEndpoint$1.call(HttpClientRestEndpoint.java:456)
	at io.reactivex.internal.operators.maybe.MaybeFromCallable.subscribeActual(MaybeFromCallable.java:46)
	... 13 more
Exception in thread "RxCachedThreadScheduler-25" io.reactivex.exceptions.OnErrorNotImplementedException: Report Portal returned error
Status code: 406
Status message: Not Acceptable
Error Message: Finish launch is not allowed. Launch '5ac52005b9d8210001d82a5f' has items '[5ac52005b9d8210001d82a61,5ac52005b9d8210001d82a62,5ac52005b9d8210001d82a63,5ac52005b9d8210001d82a64,5ac52005b9d8210001d82a65,5ac52005b9d8210001d82a66,5ac52005b9d8210001d82a68,5ac52005b9d8210001d82a69,5ac52005b9d8210001d82a67,5ac52005b9d8210001d82a6a,5ac52005b9d8210001d82a6b,5ac52005b9d8210001d82a6d,5ac52005b9d8210001d82a6e,5ac52005b9d8210001d82a6f,5ac52005b9d8210001d82a6c,5ac52005b9d8210001d82a70,5ac52005b9d8210001d82a71,5ac52005b9d8210001d82a72,5ac52005b9d8210001d82a73,5ac52005b9d8210001d82a74,5ac52005b9d8210001d82a75,5ac52005b9d8210001d82a76,5ac52005b9d8210001d82a77,5ac52005b9d8210001d82a78,5ac52005b9d8210001d82a79,5ac52005b9d8210001d82a7a,5ac52006b9d8210001d82a7b,5ac52006b9d8210001d82a7c,5ac52006b9d8210001d82a7e,5ac52006b9d8210001d82a7f,5ac52006b9d8210001d82a80,5ac52006b9d8210001d82a82,5ac52006b9d8210001d82a81,5ac52006b9d8210001d82a83,5ac52006b9d8210001d82a84,5ac52006b9d8210001d82a85,5ac52006b9d8210001d82a86,5ac52006b9d8210001d82a87,5ac52006b9d8210001d82a88,5ac52023b9d8210001d82aae,5ac52023b9d8210001d82aaf,5ac52023b9d8210001d82ab0,5ac52023b9d8210001d82ab1,5ac52023b9d8210001d82ab2,5ac52023b9d8210001d82ab4,5ac52023b9d8210001d82ab3,5ac52023b9d8210001d82ab5,5ac52023b9d8210001d82ab6,5ac52023b9d8210001d82ab7,5ac52023b9d8210001d82ab8,5ac52023b9d8210001d82ab9,5ac52023b9d8210001d82aba]' with 'IN_PROGRESS' status
Error Type: FINISH_LAUNCH_NOT_ALLOWED

	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
	at io.reactivex.internal.operators.maybe.MaybeCallbackObserver.onError(MaybeCallbackObserver.java:83)
	at io.reactivex.internal.operators.maybe.MaybeSubscribeOn$SubscribeOnMaybeObserver.onError(MaybeSubscribeOn.java:96)
	at io.reactivex.internal.operators.maybe.MaybeCache.onError(MaybeCache.java:103)
	at io.reactivex.internal.operators.maybe.MaybeFromCallable.subscribeActual(MaybeFromCallable.java:50)
	at io.reactivex.Maybe.subscribe(Maybe.java:3727)
	at io.reactivex.internal.operators.maybe.MaybeCache.subscribeActual(MaybeCache.java:77)
	at io.reactivex.Maybe.subscribe(Maybe.java:3727)
	at io.reactivex.internal.operators.maybe.MaybeSubscribeOn$SubscribeTask.run(MaybeSubscribeOn.java:54)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.epam.reportportal.exception.ReportPortalException: Report Portal returned error
Status code: 406
Status message: Not Acceptable
Error Message: Finish launch is not allowed. Launch '5ac52005b9d8210001d82a5f' has items '[5ac52005b9d8210001d82a61,5ac52005b9d8210001d82a62,5ac52005b9d8210001d82a63,5ac52005b9d8210001d82a64,5ac52005b9d8210001d82a65,5ac52005b9d8210001d82a66,5ac52005b9d8210001d82a68,5ac52005b9d8210001d82a69,5ac52005b9d8210001d82a67,5ac52005b9d8210001d82a6a,5ac52005b9d8210001d82a6b,5ac52005b9d8210001d82a6d,5ac52005b9d8210001d82a6e,5ac52005b9d8210001d82a6f,5ac52005b9d8210001d82a6c,5ac52005b9d8210001d82a70,5ac52005b9d8210001d82a71,5ac52005b9d8210001d82a72,5ac52005b9d8210001d82a73,5ac52005b9d8210001d82a74,5ac52005b9d8210001d82a75,5ac52005b9d8210001d82a76,5ac52005b9d8210001d82a77,5ac52005b9d8210001d82a78,5ac52005b9d8210001d82a79,5ac52005b9d8210001d82a7a,5ac52006b9d8210001d82a7b,5ac52006b9d8210001d82a7c,5ac52006b9d8210001d82a7e,5ac52006b9d8210001d82a7f,5ac52006b9d8210001d82a80,5ac52006b9d8210001d82a82,5ac52006b9d8210001d82a81,5ac52006b9d8210001d82a83,5ac52006b9d8210001d82a84,5ac52006b9d8210001d82a85,5ac52006b9d8210001d82a86,5ac52006b9d8210001d82a87,5ac52006b9d8210001d82a88,5ac52023b9d8210001d82aae,5ac52023b9d8210001d82aaf,5ac52023b9d8210001d82ab0,5ac52023b9d8210001d82ab1,5ac52023b9d8210001d82ab2,5ac52023b9d8210001d82ab4,5ac52023b9d8210001d82ab3,5ac52023b9d8210001d82ab5,5ac52023b9d8210001d82ab6,5ac52023b9d8210001d82ab7,5ac52023b9d8210001d82ab8,5ac52023b9d8210001d82ab9,5ac52023b9d8210001d82aba]' with 'IN_PROGRESS' status
Error Type: FINISH_LAUNCH_NOT_ALLOWED

	at com.epam.reportportal.service.ReportPortalErrorHandler.handleError(ReportPortalErrorHandler.java:57)
	at com.epam.reportportal.restendpoint.http.DefaultErrorHandler.handle(DefaultErrorHandler.java:56)
	at com.epam.reportportal.restendpoint.http.HttpClientRestEndpoint$1.call(HttpClientRestEndpoint.java:487)
	at com.epam.reportportal.restendpoint.http.HttpClientRestEndpoint$1.call(HttpClientRestEndpoint.java:456)
	at io.reactivex.internal.operators.maybe.MaybeFromCallable.subscribeActual(MaybeFromCallable.java:46)
	... 13 more
2018-04-04 21:57:46:074 +0300 [RxCachedThreadScheduler-25] ERROR com.epam.reportportal.service.Launch - [39] ReportPortal execution error
com.epam.reportportal.exception.ReportPortalException: Report Portal returned error
Status code: 406
Status message: Not Acceptable
Error Message: Finish launch is not allowed. Launch '5ac52005b9d8210001d82a5f' has items '[5ac52005b9d8210001d82a61,5ac52005b9d8210001d82a62,5ac52005b9d8210001d82a63,5ac52005b9d8210001d82a64,5ac52005b9d8210001d82a65,5ac52005b9d8210001d82a66,5ac52005b9d8210001d82a68,5ac52005b9d8210001d82a69,5ac52005b9d8210001d82a67,5ac52005b9d8210001d82a6a,5ac52005b9d8210001d82a6b,5ac52005b9d8210001d82a6d,5ac52005b9d8210001d82a6e,5ac52005b9d8210001d82a6f,5ac52005b9d8210001d82a6c,5ac52005b9d8210001d82a70,5ac52005b9d8210001d82a71,5ac52005b9d8210001d82a72,5ac52005b9d8210001d82a73,5ac52005b9d8210001d82a74,5ac52005b9d8210001d82a75,5ac52005b9d8210001d82a76,5ac52005b9d8210001d82a77,5ac52005b9d8210001d82a78,5ac52005b9d8210001d82a79,5ac52005b9d8210001d82a7a,5ac52006b9d8210001d82a7b,5ac52006b9d8210001d82a7c,5ac52006b9d8210001d82a7e,5ac52006b9d8210001d82a7f,5ac52006b9d8210001d82a80,5ac52006b9d8210001d82a82,5ac52006b9d8210001d82a81,5ac52006b9d8210001d82a83,5ac52006b9d8210001d82a84,5ac52006b9d8210001d82a85,5ac52006b9d8210001d82a86,5ac52006b9d8210001d82a87,5ac52006b9d8210001d82a88,5ac52023b9d8210001d82aae,5ac52023b9d8210001d82aaf,5ac52023b9d8210001d82ab0,5ac52023b9d8210001d82ab1,5ac52023b9d8210001d82ab2,5ac52023b9d8210001d82ab4,5ac52023b9d8210001d82ab3,5ac52023b9d8210001d82ab5,5ac52023b9d8210001d82ab6,5ac52023b9d8210001d82ab7,5ac52023b9d8210001d82ab8,5ac52023b9d8210001d82ab9,5ac52023b9d8210001d82aba]' with 'IN_PROGRESS' status
Error Type: FINISH_LAUNCH_NOT_ALLOWED

	at com.epam.reportportal.service.ReportPortalErrorHandler.handleError(ReportPortalErrorHandler.java:57)
	at com.epam.reportportal.restendpoint.http.DefaultErrorHandler.handle(DefaultErrorHandler.java:56)
	at com.epam.reportportal.restendpoint.http.HttpClientRestEndpoint$1.call(HttpClientRestEndpoint.java:487)
	at com.epam.reportportal.restendpoint.http.HttpClientRestEndpoint$1.call(HttpClientRestEndpoint.java:456)
	at io.reactivex.internal.operators.maybe.MaybeFromCallable.subscribeActual(MaybeFromCallable.java:46)
	at io.reactivex.Maybe.subscribe(Maybe.java:3727)
	at io.reactivex.internal.operators.maybe.MaybeCache.subscribeActual(MaybeCache.java:77)
	at io.reactivex.Maybe.subscribe(Maybe.java:3727)
	at io.reactivex.internal.operators.maybe.MaybeSubscribeOn$SubscribeTask.run(MaybeSubscribeOn.java:54)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Results :

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0

**Comment by Invictum** [comment]
@sirgen 
I've rechecked latest integration release on my test project and unable to reproduce an issue.
To find a root cause I need a more details:
 - what Serenity approach are you use? (jbejave, junut, etc.)
 - please provide a simple project that reproduces this issue.

Thanks in advance

**Comment by sirgen** [comment]
Hi @AliaksandrNovik , thank you.

**Comment by Invictum** [comment]
@AliaksandrNovik @sirgen 
Than you for clarification guys. I will update documentation with it.
