### ISSUE TITLE
'rp.reporting.async' is true, then launch not closing and it throws error

### ISSUE THREAD

**Issue by bvpadmanaban** [Invictum/serenity-reportportal-integration#118]
Release used - 1.5.1 or 1.5.0
Report Portal - 5.0.0

Exception in thread "Thread-1" com.epam.reportportal.exception.ReportPortalException: Report Portal returned error
Status code: 404
Status message: Not Found
Error Message: No message available
Error Type: null

	at com.epam.reportportal.service.ReportPortalErrorHandler.handleError(ReportPortalErrorHandler.java:85)
	at com.epam.reportportal.service.ReportPortalErrorHandler.handle(ReportPortalErrorHandler.java:61)
	at com.epam.reportportal.restendpoint.http.HttpClientRestEndpoint$1.subscribe(HttpClientRestEndpoint.java:526)
	at io.reactivex.internal.operators.maybe.MaybeCreate.subscribeActual(MaybeCreate.java:45)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.internal.operators.maybe.MaybeSubscribeOn$SubscribeTask.run(MaybeSubscribeOn.java:54)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by Invictum** [comment]
@bvpadmanaban 

Integration doesn't support async reporting, at least for now.

**Comment by bvpadmanaban** [comment]
> 
> 
> @bvpadmanaban
> 
> Integration doesn't support async reporting, at least for now.

Okay. Thanks.

**Comment by grey-rain** [comment]
@bvpadmanaban I know it's been a while, but I review old issues reported.
`rp.reporting.async=true` works for me in 1.6.0, at least in base cases.

**Comment by grey-rain** [comment]
abandoned.
