### ISSUE TITLE
Socket Timeout Exception after Serenity upgrade to 4.1.14

### ISSUE THREAD

**Issue by asif-choudhari** [Invictum/serenity-reportportal-integration#181]
Initially on Serenity 2.x the integration was working fine, and test were reported.
After Serenity upgrade to 4.1.14, having issue.
Add the logs for reference
`10:27:25  [rp-io-2] ERROR com.epam.reportportal.service.Launch - [28] ReportPortal execution error
10:27:25  
10:27:25  java.net.SocketTimeoutException: timeout
10:27:25  
10:27:25  
10:27:25  	at okio.Okio$4.newTimeoutException(Okio.java:232)
10:27:25  
10:27:25  
10:27:25  	at okio.AsyncTimeout.exit(AsyncTimeout.java:286)
10:27:25  
10:27:25  
10:27:25  	at okio.AsyncTimeout$2.read(AsyncTimeout.java:241)
10:27:25  
10:27:25  
10:27:25  	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:358)
10:27:25  
10:27:25  
10:27:25  	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:230)
10:27:25  
10:27:25  
10:27:25  	at okhttp3.internal.http1.Http1ExchangeCodec.readHeaderLine(Http1ExchangeCodec.java:242)
10:27:25  
10:27:25  
10:27:25  	at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.java:213)
10:27:25  
10:27:25  
10:27:25  	at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.java:115)
10:27:25  
10:27:25  
10:27:25  	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:94)
10:27:25  
10:27:25  
10:27:25  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
10:27:25  
10:27:25  
10:27:25  	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:43)
10:27:25  
10:27:25  
10:27:25  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
10:27:25  
10:27:25  
10:27:25  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
10:27:25  
10:27:25  
10:27:25  	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
10:27:25  
10:27:25  
10:27:25  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
10:27:25  
10:27:25  
10:27:25  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
10:27:25  
10:27:25  
10:27:25  	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
10:27:25  
10:27:25  
10:27:25  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
10:27:25  
10:27:25  
10:27:25  	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
10:27:25  
10:27:25  
10:27:25  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
10:27:25  
10:27:25  
10:27:25  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
10:27:25  
10:27:25  
10:27:25  	at com.epam.reportportal.service.PathParamInterceptor.intercept(PathParamInterceptor.java:55)
10:27:25  
10:27:25  
10:27:25  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
10:27:25  
10:27:25  
10:27:25  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
10:27:25  
10:27:25  
10:27:25  	at com.epam.reportportal.service.BearerAuthInterceptor.intercept(BearerAuthInterceptor.java:39)
10:27:25  
10:27:25  
10:27:25  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
10:27:25  
10:27:25  
10:27:25  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
10:27:25  
10:27:25  
10:27:25  	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
10:27:25  
10:27:25  
10:27:25  	at okhttp3.RealCall.execute(RealCall.java:81)
10:27:25  
10:27:25  
10:27:25  	at retrofit2.OkHttpCall.execute(OkHttpCall.java:204)
10:27:25  
10:27:25  
10:27:25  	at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:46)
10:27:25  
10:27:25  
10:27:25  	at io.reactivex.Observable.subscribe(Observable.java:12267)
10:27:25  
10:27:25  
10:27:25  	at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:35)
10:27:25  
10:27:25  
10:27:25  	at io.reactivex.Observable.subscribe(Observable.java:12267)
10:27:25  
10:27:25  
10:27:25  	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
10:27:25  
10:27:25  
10:27:25  	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
10:27:25  
10:27:25  
10:27:25  	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
10:27:25  
10:27:25  
10:27:25  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
10:27:25  
10:27:25  
10:27:25  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
10:27:25  
10:27:25  
10:27:25  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
10:27:25  
10:27:25  
10:27:25  	at java.base/java.lang.Thread.run(Thread.java:829)
10:27:25  
10:27:25  
10:27:25  Caused by: java.net.SocketException: Socket closed
10:27:25  
10:27:25  
10:27:25  	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:183)
10:27:25  
10:27:25  
10:27:25  	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
10:27:25  
10:27:25  
10:27:25  	at okio.Okio$2.read(Okio.java:140)
10:27:25  
10:27:25  
10:27:25  	at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
10:27:25  
10:27:25  
10:27:25  	... 38 more
10:27:25  
10:27:25  
10:27:25  [rp-io-2] ERROR com.epam.reportportal.service.Launch - [28] ReportPortal execution error
10:27:25  
10:27:25  java.net.SocketTimeoutException: timeout
10:27:25  
10:27:25  
10:27:25  	at okio.Okio$4.newTimeoutException(Okio.java:232)
10:27:25  
10:27:25  
10:27:25  	at okio.AsyncTimeout.exit(AsyncTimeout.java:286)
10:27:25  
10:27:25  
10:27:25  	at okio.AsyncTimeout$2.read(AsyncTimeout.java:241)
10:27:25  
10:27:25  
10:27:25  	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:358)
10:27:25  
10:27:25  
10:27:25  	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:230)
10:27:25  
10:27:25  
10:27:25  	at okhttp3.internal.http1.Http1ExchangeCodec.readHeaderLine(Http1ExchangeCodec.java:242)
10:27:25  
10:27:25  
10:27:25  	at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.java:213)
10:27:25  
10:27:25  
10:27:25  	at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.java:115)
10:27:25  
10:27:25  
10:27:25  	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:94)
10:27:25  
10:27:25  
10:27:25  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
10:27:25  
10:27:25  
10:27:25  	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:43)
10:27:25  
10:27:25  
10:27:25  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
10:27:25  
10:27:25  
10:27:25  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
10:27:25  
10:27:25  
10:27:25  	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
10:27:25  
10:27:25  
10:27:25  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
10:27:25  
10:27:25  
10:27:25  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
10:27:25  
10:27:25  
10:27:25  	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
10:27:25  
10:27:25  
10:27:25  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
10:27:25  
10:27:25  
10:27:25  	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
10:27:25  
10:27:25  
10:27:25  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
10:27:25  
10:27:25  
10:27:25  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
10:27:25  
10:27:25  
10:27:25  	at com.epam.reportportal.service.PathParamInterceptor.intercept(PathParamInterceptor.java:55)
10:27:25  
10:27:25  
10:27:25  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
10:27:25  
10:27:25  
10:27:25  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
10:27:25  
10:27:25  
10:27:25  	at com.epam.reportportal.service.BearerAuthInterceptor.intercept(BearerAuthInterceptor.java:39)
10:27:25  
10:27:25  
10:27:25  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
10:27:25  
10:27:25  
10:27:25  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
10:27:25  
10:27:25  
10:27:25  	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
10:27:25  
10:27:25  
10:27:25  	at okhttp3.RealCall.execute(RealCall.java:81)
10:27:25  
10:27:25  
10:27:25  	at retrofit2.OkHttpCall.execute(OkHttpCall.java:204)
10:27:25  
10:27:25  
10:27:25  	at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:46)
10:27:25  
10:27:25  
10:27:25  	at io.reactivex.Observable.subscribe(Observable.java:12267)
10:27:25  
10:27:25  
10:27:25  	at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:35)
10:27:25  
10:27:25  
10:27:25  	at io.reactivex.Observable.subscribe(Observable.java:12267)
10:27:25  
10:27:25  
10:27:25  	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
10:27:25  
10:27:25  
10:27:25  	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
10:27:25  
10:27:25  
10:27:25  	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
10:27:25  
10:27:25  
10:27:25  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
10:27:25  
10:27:25  
10:27:25  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
10:27:25  
10:27:25  
10:27:25  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
10:27:25  
10:27:25  
10:27:25  	at java.base/java.lang.Thread.run(Thread.java:829)
10:27:25  
10:27:25  
10:27:25  Caused by: java.net.SocketException: Socket closed
10:27:25  
10:27:25  
10:27:25  	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:183)
10:27:25  
10:27:25  
10:27:25  	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
10:27:25  
10:27:25  
10:27:25  	at okio.Okio$2.read(Okio.java:140)
10:27:25  
10:27:25  
10:27:25  	at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
10:27:25  
10:27:25  
10:27:25  	... 38 more`

**Comment by grey-rain** [comment]
@asif-choudhari as of now, the latest version integration has been tested with is `4.0.21`.
your issue might be resolved by using this or lower version.
support of higher versions (4.2.0 as of today) is planned, but some critical bugs from the backlog should be addressed first.
