### ISSUE TITLE
Error java.net.MalformedURLException

### ISSUE THREAD

**Issue by automationguild** [Invictum/serenity-reportportal-integration#36]
Hi,

Not sure if this is a user error or not but any idea what would cause a "ERROR com.epam.reportportal.service.ReportPortal - Cannot build ReportPortal client
java.net.MalformedURLException" ? The URL is taking direclty from the ReportPortal SuperAdmins User profile java configuration section. All the info like rp.endpoint, rp.uuid, rp.launc, and rp.project in my reportportal.properties looks correct as well. This is the verson of Serenity being used:
<serenity.version>1.9.7</serenity.version>
<serenity.jbehave.version>1.38.0</serenity.jbehave.version>
Any ideas whay I'm doing wrong?

Cheers,

Joe

Here is full error:

[main] ERROR com.epam.reportportal.service.ReportPortal - Cannot build ReportPortal client
java.net.MalformedURLException
	at java.net.URL.<init>(URL.java:627)
	at java.net.URL.<init>(URL.java:490)
	at java.net.URL.<init>(URL.java:439)
	at com.epam.reportportal.service.ReportPortal$Builder.defaultClient(ReportPortal.java:301)
	at com.epam.reportportal.service.ReportPortal$Builder.buildClient(ReportPortal.java:263)
	at com.epam.reportportal.service.ReportPortal$Builder.build(ReportPortal.java:251)
	at com.github.invictum.reportportal.injector.ReportLaunchProvider.get(ReportLaunchProvider.java:20)
	at com.github.invictum.reportportal.injector.ReportLaunchProvider.get(ReportLaunchProvider.java:14)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
	at com.google.inject.internal.BoundProviderFactory.provision(BoundProviderFactory.java:72)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:61)
	at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:62)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.SingleFieldInjector.inject(SingleFieldInjector.java:54)
	at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:132)
	at com.google.inject.internal.MembersInjectorImpl$1.call(MembersInjectorImpl.java:93)
	at com.google.inject.internal.MembersInjectorImpl$1.call(MembersInjectorImpl.java:80)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
	at com.google.inject.internal.MembersInjectorImpl.injectAndNotify(MembersInjectorImpl.java:80)
	at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:62)
	at com.google.inject.internal.InjectorImpl.injectMembers(InjectorImpl.java:987)
	at com.github.invictum.reportportal.handler.FlatHandler.<init>(FlatHandler.java:36)
	at com.github.invictum.reportportal.ReportPortalListener.<init>(ReportPortalListener.java:25)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at net.thucydides.core.steps.StepEventBus.getCustomListeners(StepEventBus.java:200)
	at net.thucydides.core.steps.StepEventBus.getAllListeners(StepEventBus.java:185)
	at net.thucydides.core.steps.StepEventBus.testSuiteFinished(StepEventBus.java:562)
	at net.serenitybdd.jbehave.runners.SerenityReportingRunner.shutdownTestSuite(SerenityReportingRunner.java:225)
	at net.serenitybdd.jbehave.runners.SerenityReportingRunner.run(SerenityReportingRunner.java:209)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: java.lang.NullPointerException
	at java.net.URL.<init>(URL.java:532)
	... 46 more
[main] ERROR com.epam.reportportal.service.ReportPortal - Cannot build ReportPortal client
com.epam.reportportal.exception.InternalReportPortalClientException: Cannot build ReportPortal client
	at com.epam.reportportal.service.ReportPortal$Builder.buildClient(ReportPortal.java:270)
	at com.epam.reportportal.service.ReportPortal$Builder.build(ReportPortal.java:251)
	at com.github.invictum.reportportal.injector.ReportLaunchProvider.get(ReportLaunchProvider.java:20)
	at com.github.invictum.reportportal.injector.ReportLaunchProvider.get(ReportLaunchProvider.java:14)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
	at com.google.inject.internal.BoundProviderFactory.provision(BoundProviderFactory.java:72)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:61)
	at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:62)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.SingleFieldInjector.inject(SingleFieldInjector.java:54)
	at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:132)
	at com.google.inject.internal.MembersInjectorImpl$1.call(MembersInjectorImpl.java:93)
	at com.google.inject.internal.MembersInjectorImpl$1.call(MembersInjectorImpl.java:80)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
	at com.google.inject.internal.MembersInjectorImpl.injectAndNotify(MembersInjectorImpl.java:80)
	at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:62)
	at com.google.inject.internal.InjectorImpl.injectMembers(InjectorImpl.java:987)
	at com.github.invictum.reportportal.handler.FlatHandler.<init>(FlatHandler.java:36)
	at com.github.invictum.reportportal.ReportPortalListener.<init>(ReportPortalListener.java:25)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at net.thucydides.core.steps.StepEventBus.getCustomListeners(StepEventBus.java:200)
	at net.thucydides.core.steps.StepEventBus.getAllListeners(StepEventBus.java:185)
	at net.thucydides.core.steps.StepEventBus.testSuiteFinished(StepEventBus.java:562)
	at net.serenitybdd.jbehave.runners.SerenityReportingRunner.shutdownTestSuite(SerenityReportingRunner.java:225)
	at net.serenitybdd.jbehave.runners.SerenityReportingRunner.run(SerenityReportingRunner.java:209)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: java.net.MalformedURLException
	at java.net.URL.<init>(URL.java:627)
	at java.net.URL.<init>(URL.java:490)
	at java.net.URL.<init>(URL.java:439)
	at com.epam.reportportal.service.ReportPortal$Builder.defaultClient(ReportPortal.java:301)
	at com.epam.reportportal.service.ReportPortal$Builder.buildClient(ReportPortal.java:263)
	... 42 more
Caused by: java.lang.NullPointerException
	at java.net.URL.<init>(URL.java:532)
	... 46 more
[main] ERROR net.thucydides.core.steps.StepEventBus - Could not instantiate listener 
java.util.ServiceConfigurationError: net.thucydides.core.steps.StepListener: Provider com.github.invictum.reportportal.ReportPortalListener could not be instantiated
	at java.util.ServiceLoader.fail(ServiceLoader.java:232)
	at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at net.thucydides.core.steps.StepEventBus.getCustomListeners(StepEventBus.java:200)
	at net.thucydides.core.steps.StepEventBus.getAllListeners(StepEventBus.java:185)
	at net.thucydides.core.steps.StepEventBus.testSuiteFinished(StepEventBus.java:562)
	at net.serenitybdd.jbehave.runners.SerenityReportingRunner.shutdownTestSuite(SerenityReportingRunner.java:225)
	at net.serenitybdd.jbehave.runners.SerenityReportingRunner.run(SerenityReportingRunner.java:209)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error in custom provider, com.epam.reportportal.exception.InternalReportPortalClientException: Cannot build ReportPortal client
  while locating com.github.invictum.reportportal.injector.ReportLaunchProvider
  at com.github.invictum.reportportal.injector.SerenityPortalModule.configure(SerenityPortalModule.java:13)
  while locating com.epam.reportportal.service.Launch
    for field at com.github.invictum.reportportal.handler.FlatHandler.launch(FlatHandler.java:35)
  while locating com.github.invictum.reportportal.handler.FlatHandler

1 error
	at com.google.inject.internal.Errors.throwProvisionExceptionIfErrorsExist(Errors.java:486)
	at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:67)
	at com.google.inject.internal.InjectorImpl.injectMembers(InjectorImpl.java:987)
	at com.github.invictum.reportportal.handler.FlatHandler.<init>(FlatHandler.java:36)
	at com.github.invictum.reportportal.ReportPortalListener.<init>(ReportPortalListener.java:25)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
	... 14 more
Caused by: com.epam.reportportal.exception.InternalReportPortalClientException: Cannot build ReportPortal client
	at com.epam.reportportal.service.ReportPortal$Builder.build(ReportPortal.java:255)
	at com.github.invictum.reportportal.injector.ReportLaunchProvider.get(ReportLaunchProvider.java:20)
	at com.github.invictum.reportportal.injector.ReportLaunchProvider.get(ReportLaunchProvider.java:14)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
	at com.google.inject.internal.BoundProviderFactory.provision(BoundProviderFactory.java:72)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:61)
	at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:62)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.SingleFieldInjector.inject(SingleFieldInjector.java:54)
	at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:132)
	at com.google.inject.internal.MembersInjectorImpl$1.call(MembersInjectorImpl.java:93)
	at com.google.inject.internal.MembersInjectorImpl$1.call(MembersInjectorImpl.java:80)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
	at com.google.inject.internal.MembersInjectorImpl.injectAndNotify(MembersInjectorImpl.java:80)
	at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:62)
	... 23 more
Caused by: com.epam.reportportal.exception.InternalReportPortalClientException: Cannot build ReportPortal client
	at com.epam.reportportal.service.ReportPortal$Builder.buildClient(ReportPortal.java:270)
	at com.epam.reportportal.service.ReportPortal$Builder.build(ReportPortal.java:251)
	... 41 more
Caused by: java.net.MalformedURLException
	at java.net.URL.<init>(URL.java:627)
	at java.net.URL.<init>(URL.java:490)
	at java.net.URL.<init>(URL.java:439)
	at com.epam.reportportal.service.ReportPortal$Builder.defaultClient(ReportPortal.java:301)
	at com.epam.reportportal.service.ReportPortal$Builder.buildClient(ReportPortal.java:263)
	... 42 more
Caused by: java.lang.NullPointerException
	at java.net.URL.<init>(URL.java:532)
	... 46 more

**Comment by Invictum** [comment]
Hi @automationguild 
It is hard to say exactly, but it looks like Report Portal client configuration issue. Can you provide a URL here? You may mask real domain name with some fake value for security reasons.

**Comment by automationguild** [comment]
Thanks @Invictum for getting back to me. Here is the reportportal.properties info (I work for a large company and I'm guessing this is probably some proxy/security issue on my end :(

rp.endpoint = http://01.922.361.67
rp.uuid = 8834b8b5-7fd6-5234-98cb-9ff1a23d7737
rp.launch = superadmin_TEST_EXAMPLE
rp.project = testProject

**Comment by Invictum** [comment]
@automationguild 
URL looks fine and works for me - at least client is build.

Maybe you have some hidden proxy configuration. Let's see what following code returns for you
```
ReportPortal.builder().build().getParameters().getBaseUrl();
```
You may evaluate it somewhere before test init.

**Comment by automationguild** [comment]
@Invictum awesme getting closer! Now getting this error:

[rp-io-3] ERROR com.epam.reportportal.service.Launch - [55] ReportPortal execution error
com.epam.reportportal.exception.ReportPortalException: Report Portal returned error
Status code: 406
Status message: Not Acceptable
Error Message: Finish launch is not allowed. Launch '5b4607be42eba40001f94368' has items '[5b4607be42eba40001f9436a,5b4607cc42eba40001f9436b]' with 'IN_PROGRESS' status
Error Type: FINISH_LAUNCH_NOT_ALLOWED

	at com.epam.reportportal.service.ReportPortalErrorHandler.handleError(ReportPortalErrorHandler.java:83)
	at com.epam.reportportal.service.ReportPortalErrorHandler.handle(ReportPortalErrorHandler.java:59)
	at com.epam.reportportal.restendpoint.http.HttpClientRestEndpoint$1.subscribe(HttpClientRestEndpoint.java:517)
	at io.reactivex.internal.operators.maybe.MaybeCreate.subscribeActual(MaybeCreate.java:45)
	at io.reactivex.Maybe.subscribe(Maybe.java:3727)
	at io.reactivex.internal.operators.maybe.MaybeCache.subscribeActual(MaybeCache.java:77)
	at io.reactivex.Maybe.subscribe(Maybe.java:3727)
	at io.reactivex.internal.operators.maybe.MaybeSubscribeOn$SubscribeTask.run(MaybeSubscribeOn.java:54)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

**Comment by Invictum** [comment]
@automationguild 
Do you run tests in parallel? And share your `pom.xml` file.

**Comment by automationguild** [comment]
No not running in parallel.  I'm using buld 4.1.0. Going thru this thread now to see what else I missed: https://github.com/reportportal/reportportal/issues/126

**Comment by Invictum** [comment]
And what about your `pom.xml` file?

**Comment by automationguild** [comment]
This is whats in my pom

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

	<modelVersion>4.0.0</modelVersion>
	<groupId>com.framework</groupId>
	<artifactId>BDD</artifactId>
	<version>1.0-SNAPSHOT</version>

	<name>GE Workflow BDD Tests</name>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<serenity.version>1.9.7</serenity.version>
		<serenity.jbehave.version>1.38.0</serenity.jbehave.version>
		<webdriver.driver>chrome</webdriver.driver>
	</properties>

	<repositories>
		<repository>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
			<id>central</id>
			<name>bintray</name>
			<url>http://jcenter.bintray.com</url>
		</repository>
		<repository>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
			<id>bintray-epam-reportportal</id>
			<name>bintray</name>
			<url>http://dl.bintray.com/epam/reportportal</url>
		</repository>
	</repositories>

	<pluginRepositories>
		<pluginRepository>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
			<id>central</id>
			<name>bintray-plugins</name>
			<url>http://jcenter.bintray.com</url>
		</pluginRepository>
	</pluginRepositories>


	

	<dependencies>
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-core</artifactId>
			<version>${serenity.version}</version>
		</dependency>
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-jbehave</artifactId>
			<version>${serenity.jbehave.version}</version>
		</dependency>
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-junit</artifactId>
			<version>${serenity.version}</version>
		</dependency>

		
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-rest-assured</artifactId>
			<version>${serenity.version}</version>
		</dependency>


		
		<dependency>
			<groupId>com.github.valfirst</groupId>
			<artifactId>jbehave-junit-runner</artifactId>
			<version>2.1.2</version>
		</dependency>

		
		<dependency>
			<groupId>com.thoughtworks.paranamer</groupId>
			<artifactId>paranamer</artifactId>
			<version>2.8</version>
		</dependency>

		
		<dependency>
			<groupId>commons-logging</groupId>
			<artifactId>commons-logging</artifactId>
			<version>1.2</version>
		</dependency>

		
		<dependency>
			<groupId>org.reflections</groupId>
			<artifactId>reflections</artifactId>
			<version>0.9.11</version>
		</dependency>

		
		<dependency>
			<groupId>com.sun.jna</groupId>
			<artifactId>jna</artifactId>
			<version>3.0.9</version>
		</dependency>

		
		<dependency>
			<groupId>net.java.dev.jna</groupId>
			<artifactId>jna-platform</artifactId>
			<version>4.5.1</version>
		</dependency>

		
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-lang3</artifactId>
			<version>3.7</version>
		</dependency>


		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-simple</artifactId>
			<version>1.7.7</version>
		</dependency>
		<dependency>
			<groupId>org.easytesting</groupId>
			<artifactId>fest-assert</artifactId>
			<version>1.4</version>
		</dependency>
		<dependency>
			<groupId>com.googlecode.json-simple</groupId>
			<artifactId>json-simple</artifactId>
			<version>1.1</version>
		</dependency>
		<dependency>
			<groupId>com.jayway.restassured</groupId>
			<artifactId>rest-assured</artifactId>
			<version>2.4.0</version>
			<exclusions>
				<exclusion>
					<groupId>org.codehaus.groovy</groupId>
					<artifactId>groovy</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.codehaus.groovy</groupId>
			<artifactId>groovy-all</artifactId>
			
			<version>2.4.15</version>
		</dependency>

		<dependency>
			<groupId>com.jayway.restassured</groupId>
			<artifactId>json-schema-validator</artifactId>
			<version>2.4.0</version>
		</dependency>

		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.12</version>

		</dependency>

		<dependency>
			<groupId>com.googlecode.lambdaj</groupId>
			<artifactId>lambdaj</artifactId>
			<version>2.3.3</version>
		</dependency>

		
		<dependency>
			<groupId>log4j</groupId>
			<artifactId>log4j</artifactId>
			<version>1.2.17</version>
		</dependency>

		<dependency>
			<groupId>org.dbunit</groupId>
			<artifactId>dbunit</artifactId>
			<version>2.4.3</version>
		</dependency>

		<dependency>
			<groupId>org.fusesource.hawtjni</groupId>
			<artifactId>hawtjni-runtime</artifactId>
			<version>1.8</version>
		</dependency>

		<dependency>
			<groupId>net.sourceforge.jtds</groupId>
			<artifactId>jtds</artifactId>
			<version>1.3.1</version>
		</dependency>

		<dependency>
			<groupId>com.sybase.jdbc3.jdbc</groupId>
			<artifactId>jconn3</artifactId>
			<version>6.05</version>
		</dependency>

		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>jetty-repacked</artifactId>
			<version>7.6.1.1</version>
		</dependency>

		<dependency>
			<groupId>org.apache.maven.plugins</groupId>
			<artifactId>maven-checkstyle-plugin</artifactId>
			<version>2.12.1</version>
		</dependency>

		<dependency>
			<groupId>org.glassfish</groupId>
			<artifactId>javax.json</artifactId>
			<version>1.0.4</version>
		</dependency>

		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-api</artifactId>
			<version>2.0-rc1</version>
		</dependency>

		<dependency>
			<groupId>com.applitools</groupId>
			<artifactId>eyes-selenium-java</artifactId>
			<version>2.51</version>
			<exclusions>
				<exclusion>
					<groupId>avalon-framework</groupId>
					<artifactId>avalon-framework</artifactId>
				</exclusion>
				<exclusion>
					<artifactId>java-client</artifactId>
					<groupId>io.appium</groupId>
				</exclusion>
				<exclusion>
					<artifactId>selenium-java</artifactId>
					<groupId>org.seleniumhq.selenium</groupId>
				</exclusion>
				<exclusion>
					<artifactId>cucumber-java</artifactId>
					<groupId>info.cukes</groupId>
				</exclusion>
			</exclusions>
		</dependency>


		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-core</artifactId>
			<version>2.0-rc1</version>
		</dependency>


		<dependency>
			<groupId>net.sf.jacob-project</groupId>
			<artifactId>jacob</artifactId>
			<version>1.14.3</version>
		</dependency>

		<dependency>
			<groupId>JAutoItX</groupId>
			<artifactId>JAutoItX</artifactId>
			<version>3.3.8.1-1.0.0-alpha</version>
			<scope>system</scope>
			<systemPath>${basedir}/lib/JAutoItX.jar</systemPath>
		</dependency>
		<dependency>
			<groupId>com.ge.dsp</groupId>
			<artifactId>dsp.event.publisher.api</artifactId>
			<version>1.7.0</version>
		</dependency>
		<dependency>
			<groupId>com.rabbitmq</groupId>
			<artifactId>amqp-client</artifactId>
			<version>2.8.4</version>
		</dependency>
		<dependency>
			<groupId>org.json</groupId>
			<artifactId>json</artifactId>
			<version>20160212</version>
		</dependency>

		<dependency>
			<groupId>com.github.invictum</groupId>
			<artifactId>serenity-reportportal-integration</artifactId>
			<version>1.1.3</version>
		</dependency>




	</dependencies>
	<build>

		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-resources-plugin</artifactId>
				<version>2.4.2</version>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-checkstyle-plugin</artifactId>
				<version>2.12.1</version>

			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>2.18.1</version>
				<configuration>
					<skip>true</skip>
				</configuration>
			</plugin>
			<plugin>
				<artifactId>maven-failsafe-plugin</artifactId>
				<version>2.18.1</version>
				<configuration>
					<includes>
						<include>**/*Test.java</include>
						<include>**/Test*.java</include>
						<include>**/When*.java</include>
						<include>**/*TestSuite.java</include>
					</includes>
					<systemPropertyVariables>
						<webdriver.driver>${webdriver.driver}</webdriver.driver>
					</systemPropertyVariables>
				</configuration>
				<executions>
					<execution>
						<goals>
							<goal>integration-test</goal>
							<goal>verify</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.2</version>
				<configuration>
					<source>1.7</source>
					<target>1.7</target>
				</configuration>
			</plugin>
			<plugin>
				<groupId>net.serenity-bdd.maven.plugins</groupId>
				<artifactId>serenity-maven-plugin</artifactId>
				<version>${serenity.version}</version>

				<executions>
					<execution>
						<id>serenity-reports</id>
						<phase>post-integration-test</phase>
						<goals>
							<goal>aggregate</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>

	</build>


</project>

**Comment by Invictum** [comment]
@automationguild 
Update `maven-failsafe-plugin` to version `2.19.1` or above.

**Comment by Invictum** [comment]
@automationguild 
The same as you already do in your `pom.xml`
```
<dependency>
            <groupId>com.github.invictum</groupId>
            <artifactId>serenity-reportportal-integration</artifactId>
            <version>1.1.3</version>
            <exclusions>
                <exclusion>
                    <groupId>net.serenity-bdd</groupId>
                    <artifactId>serenity-core</artifactId>
                </exclusion>
            </exclusions>
</dependency>
<dependency>
		<groupId>net.serenity-bdd</groupId>
		<artifactId>serenity-core</artifactId>
		<version>${serenity.version}</version>
</dependency>
```
Does `maven-failsafe-plugin` update to `2.19.1` solve your issue with FINISH_LAUNCH_NOT_ALLOWED error?

**Comment by automationguild** [comment]
Thanks again @Invictum for all your help. Would love to get this working but I'm still gettng the error:

com.epam.reportportal.exception.ReportPortalException: Report Portal returned error
Status code: 406
Status message: Not Acceptable
Error Message: Finish launch is not allowed. Launch '5b59b6362ab79c00016820d2' has items '[5b59b6372ab79c00016820d4,5b59b63f2ab79c00016820d5]' with 'IN_PROGRESS' status
Error Type: FINISH_LAUNCH_NOT_ALLOWED

I've added all the changes you recommended not sure what else I'm messing up.

**Comment by Invictum** [comment]
@automationguild 
Can you provide a simple project that reproduced an issue, so I may use to debug? Also specify a command you use to run test in mentioned project.

**Comment by automationguild** [comment]
@Invictum unfortunelty I can't repro in a project that I can share yet. When I create a standard Serenity project using the jbehave archetype and add the same reportportal values to the project it works. Tryin to figure out what is dif about my project. One main thing is that we name our .story files as .feature files. I run using this mvn command: 

clean verify serenity:aggregate -U -Dmaven.test.failure.ignore=true -Dwebdriver.driver=chrome -Dwebdriver.chrome.driver=./chromedriver.exe -Dwebdriver.base.url=https://11.77.000.268 -Dstory.timeout.in.secs=7200 -Dignore.failure.in.stories=true -Dmetafilter="-skip +sanity" -s settings.xml

We also have a hack in our testsuite runner that might be causing issues:

public class RadDesktopTestSuite extends SerenityStories {
    
    public RadDesktopTestSuite() {

        String testSuitePropertyPath = System.getProperty("user.dir").
                concat("/src/test/resources/propertyfiles/testsuite.properties");
        try {
            byte[] encodedFeatureNames = Files.readAllBytes(Paths.get(testSuitePropertyPath));
            String featuresToRun = new String(encodedFeatureNames, "utf-8");
            this.findStoriesCalled(featuresToRun);
         
        }
        catch (IOException e) {
            
            e.printStackTrace();
        }

      }
    
}

**Comment by automationguild** [comment]
Anyone have any other suggestions?

**Comment by Invictum** [comment]
@automationguild 
I tested integration with mentioned maven options
```
clean verify serenity:aggregate -U -Dmaven.test.failure.ignore=true -Dwebdriver.driver=chrome -Dstory.timeout.in.secs=7200 -Dignore.failure.in.stories=true -Dmetafilter="-skip +sanity"
```
With no luck to reproduce your issue.

Integration implemented on `serenity-core` level, so it may be broken only if you alter regular serenity test lifecycle. Unfortunately it is hard to guess what is wrong without debug. And it is possible only with your projects.

I recommend you try to debug your project. You may start with `ReportPortalListener` it is an entry point for Serenity integration. Run your tests and observe a sequence of events in this class. Provide results here and I we will try to find root cause together.

**Comment by automationguild** [comment]
Thanks @Invictum for your help. I'm so close to getting this working now. I have one last hurdle but not sure if its a ReportPortal issue or a plugin issue. When I run a feature file that does not have a @skip in a Meta section the full feature file works fine and all the runs appear in ReportPortal. If I run a feature file that has multiple tests and one of them has a @skip it aborts the feature run and the results for the @skip test shows up in ReportPortal as in progress. So i guess my question is does the serenity-reportportal-integration plugin support @skip tags OR is this a ReportPortal issue? Thanks again!!!

**Comment by automationguild** [comment]
Fixed the @skip issue by using the -Dmetafilter=-skip command. All set thanks again!!
