### ISSUE TITLE
Help: Last test stuck in "In Progress" status

### ISSUE THREAD

**Issue by automationguild** [Invictum/serenity-reportportal-integration#45]
Hi,

Sorry me again.

Everything works except for each Launch the last test always get stuck in an "In Progress" .

The test eventually times out with the status of "interrupted".

Not sure if the issue is in my ReportPortal dashboard(build 4.3.0) setup of in the Serenity plugin (version 1.1.3)

Any ideas what I'm doing wrong?

Thanks again!

**Comment by Invictum** [comment]
hi,

I will try to look at it tomorrow.
Does issue reproduce with latest integration version - 1.2.1?

**Comment by automationguild** [comment]
Hi @Invictum !

I also asked the folks at ReportPortal and it sounds like its a known issue on their side :( 
==========================
This can happen when:

- when runner/framework do not send FinishRQ for launch
- when runner sends FinishRQ, but some of the test cases are still in progress. And server returns you an error, that you can't finalize parent when the child is still in progress.

Most likely you will find smth like can't finish launch in logs.
The same line you will find test case id, which is still left in progress. You also can find it via UI, when launch stay IN_progress (click launch name and go deeper into a suite which is in progress)

We keep this logic in order to help find incorrectly finished test cases. And do clean up within you tests.
But some of test runners/frameworks/engineers do not care about proper finalization, and basically, do not follow practices.
That's why we plan to suppress this check on the server side for next version (5.0) and allow to finish launch, even if test cases are still in progress.

**Comment by Invictum** [comment]
Integration emmits finish execution event on JVM shutdown.
May you attach logs of your execution?

**Comment by automationguild** [comment]
Sure which logs do you want? This is from the failsafe-reports (I also noticed that the Serenity index.html is blank)

-------------------------------------------------------------------------------

Test set: com.ge.hcit.radtests.bdd.RadDesktopTestSuite

-------------------------------------------------------------------------------

Tests run: 204, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 209.726 sec <<< FAILURE! - in com.ge.hcit.radtests.bdd.RadDesktopTestSuite

com.ge.hcit.radtests.bdd.RadDesktopTestSuite  Time elapsed: 22.091 sec  <<< ERROR!

net.serenitybdd.core.exceptions.SerenityManagedException: Exceptions thrown with messages:"null" ;

                at net.serenitybdd.jbehave.embedders.monitors.CompositeEmbedderMonitor.processSuppressed(CompositeEmbedderMonitor.java:577)

                at net.serenitybdd.jbehave.embedders.monitors.CompositeEmbedderMonitor.storiesNotAllowed(CompositeEmbedderMonitor.java:194)

                at org.jbehave.core.embedder.StoryManager.performStories(StoryManager.java:125)

                at org.jbehave.core.embedder.StoryManager.runStories(StoryManager.java:107)

                at org.jbehave.core.embedder.StoryManager.runStoriesAsPaths(StoryManager.java:86)

                at org.jbehave.core.embedder.Embedder.runStoriesAsPaths(Embedder.java:213)

                at net.serenitybdd.jbehave.embedders.ExtendedEmbedder.runStoriesAsPaths(ExtendedEmbedder.java:60)

                at net.serenitybdd.jbehave.runners.SerenityReportingRunner.run(SerenityReportingRunner.java:203)

                at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)

                at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)

                at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)

                at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)

**Comment by Invictum** [comment]
Logs that appears in a console. Underlying RP client sends communication errors here.

In accordance to output you provided something wrong happens with Serenity itself. Does it work with disabled integration?

**Comment by Invictum** [comment]
Issue is closed due to lack of activity. Please create a new one if it is still occurred.
