### ISSUE TITLE
ReportPortalListener could not be instantiated

### ISSUE THREAD

**Issue by pramodhnv** [Invictum/serenity-reportportal-integration#88]
Hi @Invictum ,

We are trying to integrate our serenity cucumber framework, versions are below

     <serenity.version>2.0.70</serenity.version>
        <serenity.cucumber.version>1.9.45</serenity.cucumber.version>

During execution, it fails with below error. Could you please help.

[ERROR] 2019-11-18 14:27:07.105 :: Could not instantiate listener 
java.util.ServiceConfigurationError: net.thucydides.core.steps.StepListener: Provider com.github.invictum.reportportal.ReportPortalListener could not be instantiated
	at java.util.ServiceLoader.fail(ServiceLoader.java:232) ~[?:1.8.0_181]
	at java.util.ServiceLoader.access$100(ServiceLoader.java:185) ~[?:1.8.0_181]
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384) ~[?:1.8.0_181]
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404) ~[?:1.8.0_181]
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480) ~[?:1.8.0_181]
	at net.thucydides.core.steps.StepEventBus.getCustomListeners(StepEventBus.java:207) ~[serenity-core-2.0.70.jar:2.0.70]
	at net.thucydides.core.steps.StepEventBus.getAllListeners(StepEventBus.java:192) ~[serenity-core-2.0.70.jar:2.0.70]
	at net.thucydides.core.steps.StepEventBus.testSuiteStarted(StepEventBus.java:247) ~[serenity-core-2.0.70.jar:2.0.70]
	at cucumber.runtime.formatter.SerenityReporter.lambda$handleTestSourceRead$8(SerenityReporter.java:174) ~[serenity-cucumber-1.9.45.jar:?]
	at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_181]
	at cucumber.runtime.formatter.SerenityReporter.handleTestSourceRead(SerenityReporter.java:166) ~[serenity-cucumber-1.9.45.jar:?]
	at cucumber.runtime.formatter.SerenityReporter.lambda$new$0(SerenityReporter.java:125) ~[serenity-cucumber-1.9.45.jar:?]
	at cucumber.runner.EventBus.send(EventBus.java:28) [cucumber-core-2.4.0.jar:?]
	at cucumber.runtime.model.CucumberFeature.sendTestSourceRead(CucumberFeature.java:132) [cucumber-core-2.4.0.jar:?]
	at cucumber.runtime.RuntimeOptions.cucumberFeatures(RuntimeOptions.java:315) [cucumber-core-2.4.0.jar:?]
	at cucumber.api.junit.Cucumber.<init>(Cucumber.java:81) [cucumber-junit-2.4.0.jar:?]
	at net.serenitybdd.cucumber.CucumberWithSerenity.<init>(CucumberWithSerenity.java:54) [serenity-cucumber-1.9.45.jar:1.9.45]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) [?:1.8.0_181]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) [?:1.8.0_181]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [?:1.8.0_181]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) [?:1.8.0_181]
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104) [junit-4.12.jar:4.12]
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86) [junit-4.12.jar:4.12]
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59) [junit-4.12.jar:4.12]
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26) [junit-4.12.jar:4.12]
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59) [junit-4.12.jar:4.12]
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33) [junit-4.12.jar:4.12]
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:49) [junit-rt.jar:?]
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47) [junit-rt.jar:?]
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242) [junit-rt.jar:?]
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70) [junit-rt.jar:?]
Caused by: java.lang.NoClassDefFoundError: com/epam/reportportal/service/Launch
	at com.github.invictum.reportportal.injector.SerenityPortalModule.configure(SerenityPortalModule.java:14) ~[serenity-reportportal-integration-1.4.2.jar:?]
	at com.google.inject.AbstractModule.configure(AbstractModule.java:61) ~[guice-4.2.2.jar:?]
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:344) ~[guice-4.2.2.jar:?]
	at com.google.inject.spi.Elements.getElements(Elements.java:103) ~[guice-4.2.2.jar:?]
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:137) ~[guice-4.2.2.jar:?]
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:103) ~[guice-4.2.2.jar:?]
	at com.google.inject.Guice.createInjector(Guice.java:87) ~[guice-4.2.2.jar:?]
	at com.google.inject.Guice.createInjector(Guice.java:69) ~[guice-4.2.2.jar:?]
	at com.google.inject.Guice.createInjector(Guice.java:59) ~[guice-4.2.2.jar:?]
	at com.github.invictum.reportportal.injector.IntegrationInjector.getInjector(IntegrationInjector.java:17) ~[serenity-reportportal-integration-1.4.2.jar:?]
	at com.github.invictum.reportportal.ReportPortalListener.<init>(ReportPortalListener.java:26) ~[serenity-reportportal-integration-1.4.2.jar:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_181]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_181]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_181]
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_181]
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380) ~[?:1.8.0_181]
	... 28 more
Caused by: java.lang.ClassNotFoundException: com.epam.reportportal.service.Launch
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_181]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_181]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349) ~[?:1.8.0_181]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_181]
	at com.github.invictum.reportportal.injector.SerenityPortalModule.configure(SerenityPortalModule.java:14) ~[serenity-reportportal-integration-1.4.2.jar:?]
	at com.google.inject.AbstractModule.configure(AbstractModule.java:61) ~[guice-4.2.2.jar:?]
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:344) ~[guice-4.2.2.jar:?]
	at com.google.inject.spi.Elements.getElements(Elements.java:103) ~[guice-4.2.2.jar:?]
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:137) ~[guice-4.2.2.jar:?]
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:103) ~[guice-4.2.2.jar:?]
	at com.google.inject.Guice.createInjector(Guice.java:87) ~[guice-4.2.2.jar:?]
	at com.google.inject.Guice.createInjector(Guice.java:69) ~[guice-4.2.2.jar:?]
	at com.google.inject.Guice.createInjector(Guice.java:59) ~[guice-4.2.2.jar:?]
	at com.github.invictum.reportportal.injector.IntegrationInjector.getInjector(IntegrationInjector.java:17) ~[serenity-reportportal-integration-1.4.2.jar:?]
	at com.github.invictum.reportportal.ReportPortalListener.<init>(ReportPortalListener.java:26) ~[serenity-reportportal-integration-1.4.2.jar:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_181]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_181]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_181]
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_181]
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380) ~[?:1.8.0_181]
	... 28 more

**Comment by pramodhnv** [comment]
reportportal.properties:
rp.endpoint = http://localhost:8080
rp.uuid = bef4a299-ff15-455e-bad5-3ec7598ce67f
rp.launch = superadmin_TEST_EXAMPLE
rp.project = SynBDD

**Comment by Invictum** [comment]
@pramodhnv 
Thanks for issue reporting. Can you provide simple project that reproduces an issue?

**Comment by Invictum** [comment]
@pramodhnv 
I'm unable to reproduce this issue, so I will close a ticket. If you will face with it one more time create a new one.
